name: MLExplorer
options:
  bundleIdPrefix: com.mlexplorer
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15"

targets:
  MLExplorer:
    type: application
    platform: iOS
    sources:
      - MLExplorer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mlexplorer.app
        SWIFT_VERSION: 5.9
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: MLExplorer/Info.plist
        DEVELOPMENT_TEAM: BVTP4744AS
        CODE_SIGN_STYLE: Automatic
    entitlements:
      path: MLExplorer/MLExplorer.entitlements
      properties:

  MLExplorerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MLExplorerTests
    dependencies:
      - target: MLExplorer
    settings:
      base:
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: BVTP4744AS
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.mlexplorer.tests
        GENERATE_INFOPLIST_FILE: YES

  MLExplorerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - MLExplorerUITests
    dependencies:
      - target: MLExplorer
    settings:
      base:
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: BVTP4744AS
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.mlexplorer.uitests
        GENERATE_INFOPLIST_FILE: YES
